<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>0.0.1</Version>
        <!-- The two lines below will set the output path for the binaries -->
        <OutputPath>M:\Work\MyRawMod\Builds\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <!-- Disable PDB file generation -->
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <!-- Disable generation of deps.json file -->
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
        <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
        <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    </ItemGroup>
    <ItemGroup>
        <Content Include=".git\config" />
        <Content Include=".git\description" />
        <Content Include=".git\FETCH_HEAD" />
        <Content Include=".git\HEAD" />
        <Content Include=".git\hooks\applypatch-msg.sample" />
        <Content Include=".git\hooks\commit-msg.sample" />
        <Content Include=".git\hooks\fsmonitor-watchman.sample" />
        <Content Include=".git\hooks\post-update.sample" />
        <Content Include=".git\hooks\pre-applypatch.sample" />
        <Content Include=".git\hooks\pre-commit.sample" />
        <Content Include=".git\hooks\pre-merge-commit.sample" />
        <Content Include=".git\hooks\pre-push.sample" />
        <Content Include=".git\hooks\pre-rebase.sample" />
        <Content Include=".git\hooks\pre-receive.sample" />
        <Content Include=".git\hooks\prepare-commit-msg.sample" />
        <Content Include=".git\hooks\push-to-checkout.sample" />
        <Content Include=".git\hooks\sendemail-validate.sample" />
        <Content Include=".git\hooks\update.sample" />
        <Content Include=".git\index" />
        <Content Include=".git\info\exclude" />
        <Content Include=".git\logs\HEAD" />
        <Content Include=".git\logs\refs\heads\master" />
        <Content Include=".git\logs\refs\remotes\origin\master" />
        <Content Include=".git\objects\03\55c7978bf7d1948cd86a4a13dcbd95296b2426" />
        <Content Include=".git\objects\05\f24d8bc0e5f56611fa623a16916befbfea7101" />
        <Content Include=".git\objects\06\df3c673f85714b732dfc9ce0dc04ee331f1691" />
        <Content Include=".git\objects\07\2d0d1e43a2cacd1377af45b0b64d0f9beedd0b" />
        <Content Include=".git\objects\09\009ab86e43d85d4af87c602568719232bad002" />
        <Content Include=".git\objects\09\14aa2d4392cc709156a9102a639bd37f4145cc" />
        <Content Include=".git\objects\0a\4be4925d8723b07c2c621e60f7fb00d94fea13" />
        <Content Include=".git\objects\0d\38d3194a05071dc1bb1194bbc3fc46b21f955b" />
        <Content Include=".git\objects\0d\b8b6a558e55adbb0ab6972cf3e4f874a77128f" />
        <Content Include=".git\objects\0e\0dcd235c4973becf25f38eb4e5bb26e154c86a" />
        <Content Include=".git\objects\0f\52f0c0531462e09f38d0c2a30fa7694d9d4f82" />
        <Content Include=".git\objects\0f\82d88a5459574f9b9bf840aae4e1ebc3b968cf" />
        <Content Include=".git\objects\10\ac1d2665b3a8bcbe8d5aa9e60547204b544cda" />
        <Content Include=".git\objects\11\b3de955071dcccf3502f195b2eb3b1a0494a9b" />
        <Content Include=".git\objects\12\14e3fd8a859ca262ff11d7ada806f88c3dc4c7" />
        <Content Include=".git\objects\14\07991b477ee007c6be48bdff5d84be5ae9d9d3" />
        <Content Include=".git\objects\15\cdbe83454ad71d23e2b3b2dae340bbcfcffb0c" />
        <Content Include=".git\objects\17\1cff621be57d4afcca4b87d7da11cdff06f983" />
        <Content Include=".git\objects\17\e1bfd4dd2a7bfc532fe6e888e5918f97e1f202" />
        <Content Include=".git\objects\18\735f93b243c4f3960f64b964366339fcc60ea2" />
        <Content Include=".git\objects\18\dbcc2617fb1bd4b78422ddca0c39b4ed530d0d" />
        <Content Include=".git\objects\19\8fd3e8c161fdcc31b308fa092b345e46b1607e" />
        <Content Include=".git\objects\19\c66898e4b0f3d55a712ed0adf50356aa41bf55" />
        <Content Include=".git\objects\1a\4e19e16e23813ec315b2383921aa6c3449e1a0" />
        <Content Include=".git\objects\1a\c6ec0c4d13857f4dfe57c67694104a13cb0be5" />
        <Content Include=".git\objects\1b\84224b924d9fc86b368719e259b466e8d95676" />
        <Content Include=".git\objects\1b\9b8753de311143ee14863ffda7171d21b37544" />
        <Content Include=".git\objects\1d\56fbd2365c2850bcdd9dc5fce34c79bf7b22ae" />
        <Content Include=".git\objects\1d\9fb357158ab6f5b76be0d85795fd3e93a954bf" />
        <Content Include=".git\objects\1d\b0169d26e3d8a97e4c7351aab66ab575779a07" />
        <Content Include=".git\objects\1f\f3693c39b0ffc6aa65a4386a9c10a84c065f34" />
        <Content Include=".git\objects\23\c35ac3e64f147f82a8bb4b03a6232da8f4ae0f" />
        <Content Include=".git\objects\26\ab3d3d9455b29f411e185d8ba2d6ef5bd732cc" />
        <Content Include=".git\objects\28\94114f376da9b98713fea790efe4c1d34887a4" />
        <Content Include=".git\objects\29\7e2e4fe8b4d99d3de4665daffd9a00541bdc11" />
        <Content Include=".git\objects\2d\3fbcddcef4f2349dbf2a667c20fc5ecbcbcc49" />
        <Content Include=".git\objects\2e\09631041028b5c7c9a36cd7b631821681d671e" />
        <Content Include=".git\objects\2e\f01712ec79e69a2a4744df7a130efd7fd09d26" />
        <Content Include=".git\objects\31\c76f58b6eba042b6327e9f6a3455e3a5602670" />
        <Content Include=".git\objects\33\39f360dba2b6e1a628d8d4eb0144830b954b7d" />
        <Content Include=".git\objects\34\c0318680856b6e061041c5fff6605630c1a5df" />
        <Content Include=".git\objects\35\7c614442d17907a33b784c5fcca84895cdd250" />
        <Content Include=".git\objects\36\8a7c23f8796f1612ef8eb4d45b92e6fac3fa2d" />
        <Content Include=".git\objects\37\d24c6ec1aaf804b83d21c8740994f7e6e370bc" />
        <Content Include=".git\objects\38\92f045a62dde6b79f6ed73b2a5fcdfb47dda59" />
        <Content Include=".git\objects\39\7ea5cd24fb062a268d8357df25d66c4c237367" />
        <Content Include=".git\objects\3d\424b6095a37e48136821b4dba6ec7eb20b8ed0" />
        <Content Include=".git\objects\3f\5d243f1154366cfbef369077aa2bf964c27f57" />
        <Content Include=".git\objects\41\869c505c8f318c7409cb32a880690982d4cd1e" />
        <Content Include=".git\objects\43\e5c811e74485907e1c9b4929c6da57c938a2f9" />
        <Content Include=".git\objects\44\5d51a457f2140d5243abec80c00e531c3f58f3" />
        <Content Include=".git\objects\45\54d4422aab2cfff486bf516d6a95ae16900dc4" />
        <Content Include=".git\objects\46\fac117f10fa802e72ed9ad337c0bcf0bce087c" />
        <Content Include=".git\objects\47\91936b38a3883f95ea847e7ce7595913bc7baa" />
        <Content Include=".git\objects\49\1a80a97880de93aa893f6974c5f76891d2de73" />
        <Content Include=".git\objects\4c\749e41ef6e0d300f3a5a323a119dcb2d2f1e56" />
        <Content Include=".git\objects\4d\df3084a3455165ee339f06f78c4fe2ac6806a0" />
        <Content Include=".git\objects\4f\bc027583300b723af7e8ea5b25f7ec966bcd88" />
        <Content Include=".git\objects\50\432278b64a9618f7bc27b6712476e28e03fab7" />
        <Content Include=".git\objects\55\48ae93619be8514f02eb5ffa3dafb271b0e771" />
        <Content Include=".git\objects\57\09bbbd2176c38724015ec68def39ad615a04de" />
        <Content Include=".git\objects\57\c5e17d470b48735cc2bf06b6741a2311d9bdc9" />
        <Content Include=".git\objects\57\d2db149187d9c5bec084ad1a8bf1d5018344b2" />
        <Content Include=".git\objects\59\1fc855487d9aea336971cfba22af2c0bee9c0d" />
        <Content Include=".git\objects\5b\3e24dab3bb5f06f9d885060ababa718ce081bb" />
        <Content Include=".git\objects\5e\16cf862731f4759120928eb7ff9f4863736bd3" />
        <Content Include=".git\objects\5e\6f83c7fae08f6ca4f6f77df2be5c613e63c829" />
        <Content Include=".git\objects\5f\f9f6df85425caabb190d72f6a811565ea91182" />
        <Content Include=".git\objects\60\ca51689d6120354879426b714f65f788d7ba7a" />
        <Content Include=".git\objects\60\dca0403a2ba61eb471e8d687f3c213aa82579c" />
        <Content Include=".git\objects\62\2a9c6f6824de5693d92fb5068ff0443f190883" />
        <Content Include=".git\objects\63\6b1cd07dcb626d652392af193f0df7ca90d2ec" />
        <Content Include=".git\objects\63\8e279678a3626c95fa755a9698388230a687ab" />
        <Content Include=".git\objects\64\8b052474ff56bf90e27cbd0f356355edf3b215" />
        <Content Include=".git\objects\65\9af63c356ac70ec6b8aace2195ad6d3c4e11bd" />
        <Content Include=".git\objects\66\941f093317aab7368cd6e1fe6b77a4d75d42ec" />
        <Content Include=".git\objects\66\9aefae27e87997d4f81891824612a2b2578126" />
        <Content Include=".git\objects\66\d42f4bb0242d5e50e44ee1b8b8617d99cc6466" />
        <Content Include=".git\objects\66\eaa849914fc6dff7f7131960ffed75bcebf3e1" />
        <Content Include=".git\objects\69\f95f604422499c86fb5e419dbc918f0ecd3e1d" />
        <Content Include=".git\objects\6a\590e391dc4d7ea96b72fc7555233935e0e86e7" />
        <Content Include=".git\objects\6a\c8a800307ff52aeecf4b17d0b858f0c752be2e" />
        <Content Include=".git\objects\6b\ae1b03744258832e1ece66a09f11e4c4da01a7" />
        <Content Include=".git\objects\6f\a0c8f29549646f603d98a4e212ae085f8258e8" />
        <Content Include=".git\objects\70\b2db35bd029c063b522ee30c0a9b6776fa787c" />
        <Content Include=".git\objects\71\241422f133a8d9e8b3ad02ca5905cffddbe97f" />
        <Content Include=".git\objects\73\7d4579361ada6d414f6d15e2263b931fc76d92" />
        <Content Include=".git\objects\73\b9eebea993b3b0157c3b1bb89a657f01c8cbee" />
        <Content Include=".git\objects\74\69ce289925ebf513cc5029ef389c59f6821088" />
        <Content Include=".git\objects\77\5fbbd6ecf82f3ae93d3e915da5a636f2d5aa3c" />
        <Content Include=".git\objects\79\99838453d462b205ad61f06d217a0581b922c8" />
        <Content Include=".git\objects\7a\347fa1133709a64150f59621b8fec67c776808" />
        <Content Include=".git\objects\7d\e68f17e7a970b835860c82b591ca0643eb89bc" />
        <Content Include=".git\objects\7e\2a8bb827bd92312ed1da98d352d730a3a39498" />
        <Content Include=".git\objects\80\153e7d0900b006a686d1309d0616af7270843b" />
        <Content Include=".git\objects\82\6b3a67e32e4b243605d5a7d3a20b03adc54d08" />
        <Content Include=".git\objects\84\2e3bf5db1c4bad0d37d8baa3d82baa0e117a78" />
        <Content Include=".git\objects\86\29365de99d569ea98f86ffa835496a980ac8c8" />
        <Content Include=".git\objects\89\73b0a48c34dcd9e4ad736a71ffdad05921d4ce" />
        <Content Include=".git\objects\89\c7c11b1b3758b555cbab36105b77de2e0bdd02" />
        <Content Include=".git\objects\8a\0e7618f4f74305188b74782182471c7787a9fb" />
        <Content Include=".git\objects\8e\ae0e15ce822a5ba32a2559061ddf6245746bc2" />
        <Content Include=".git\objects\8f\2dc4cd9d9fec11114516d5ff1345566b39062d" />
        <Content Include=".git\objects\8f\806b5f9806cda41ad05cc40b3994160de5f5b1" />
        <Content Include=".git\objects\91\892ab95b4e25a6ee4f8f52011eaf5c82a549ef" />
        <Content Include=".git\objects\91\dace4476e8c5a9e0a21878fc6720116683b8e4" />
        <Content Include=".git\objects\92\f3eea93d8068ab498c3e056f8e6e72009c01d2" />
        <Content Include=".git\objects\93\fc3753581bf77a87f008adcff5e77c3869b8ab" />
        <Content Include=".git\objects\94\445c44a467ae1130b1dd9d524d92f68a3976de" />
        <Content Include=".git\objects\94\7105546bb996a320aeaec740f08c064c3d0793" />
        <Content Include=".git\objects\95\553b88ac26293e045857f04e4bc8947f6fe476" />
        <Content Include=".git\objects\96\d48cf763d723957ead6251aef5db2866907775" />
        <Content Include=".git\objects\97\d8b117612bfd0e3a88eb351aeefa69df717a41" />
        <Content Include=".git\objects\99\507441f3d14264fc67d86d733c43768cef4a1f" />
        <Content Include=".git\objects\99\9e2d4b65a81678158cbfdfe9f49585ed9059b9" />
        <Content Include=".git\objects\99\daef723fd1dd2189780b60d5a2f12c2a3e4e34" />
        <Content Include=".git\objects\9a\817c2df86b18793e3ee617ff7e5a12dbba4fd3" />
        <Content Include=".git\objects\9a\a6c13f30473a68f93db77b84b3e322588b42cc" />
        <Content Include=".git\objects\9c\1f8c671e83b2cc3c5eb0e0ef943f4e6c0c5881" />
        <Content Include=".git\objects\9d\fdab1f26032c6939477b41fe422f0b8bd7e86e" />
        <Content Include=".git\objects\9e\210740d5f20630ed574198113509fc44f92014" />
        <Content Include=".git\objects\a1\b1537eeeb818bf8197bae89745d8e290fb6850" />
        <Content Include=".git\objects\a2\d7dd0b9b890624a24bac379cc84243785793f3" />
        <Content Include=".git\objects\a5\ec96c7e3f10536b1ee9a48ed59ee6cd46af0f4" />
        <Content Include=".git\objects\a7\316cd1798aa8b0a16293c38522a94a6663c632" />
        <Content Include=".git\objects\a8\e9bd721150844984f2171791627d52fbbb9301" />
        <Content Include=".git\objects\a9\5f36f0b8bf55ba2786b4633763a3555d130579" />
        <Content Include=".git\objects\aa\d4286800cb2eb78cdf0d3c8bb367afeb2cee9c" />
        <Content Include=".git\objects\ab\c52fe0e3db988514fbcefa530e4e35c6512cc3" />
        <Content Include=".git\objects\ac\36cfa2c1805586426d2ada8b18536a5e8a74bc" />
        <Content Include=".git\objects\ac\da3df3800ea4807ec7b8c44264a4b88281db5c" />
        <Content Include=".git\objects\ae\ea7328494c0bb322e50380546fc7b88b2ca8c4" />
        <Content Include=".git\objects\af\f386f580f6a666e1f8bb4bb18fb9180ca29ea3" />
        <Content Include=".git\objects\b0\d7ca21ddece11fe815af7d25f33c5e117181ac" />
        <Content Include=".git\objects\b2\8eeb10333eca93afa916d931a19ae93557652c" />
        <Content Include=".git\objects\b4\4925ee23cb6e130cb17a69f7f51adaaa7c6139" />
        <Content Include=".git\objects\b5\5b66b45afa5526ba878ce55aaf1e9d67aa3381" />
        <Content Include=".git\objects\b6\da3f069568c44f0ef3f3dcb098bb239c93c75c" />
        <Content Include=".git\objects\b7\faffc5b31548c18368dfcddb03bbefd4a71a4f" />
        <Content Include=".git\objects\b8\d0bbb92c3b3fca0b342c59bbf5369e57af9e72" />
        <Content Include=".git\objects\bd\df5cbdb5e0fa67f1a50ffce4173d540c2fe346" />
        <Content Include=".git\objects\be\b03c6ac4ed91e5367d41e5a4d8945d09a59cb2" />
        <Content Include=".git\objects\bf\adc3c04c389037cb28ab96697cbaba0deb77dc" />
        <Content Include=".git\objects\c1\40ee8611680ea6c77844e9ca406369ea6eea45" />
        <Content Include=".git\objects\c1\499b130e7d0117e1da1ef9fad8a72d8c07dc40" />
        <Content Include=".git\objects\c2\6182217b66ce1b58eae229409b74c7a11967d3" />
        <Content Include=".git\objects\c3\082c9edb3dbdbdf5e50defacfe59ee6d4e7ef8" />
        <Content Include=".git\objects\c4\f90d067b799d4b8b6c9380d6a46da533bf56fd" />
        <Content Include=".git\objects\c5\6ce64f043ab94a57d968424c3f8a1138fd05d3" />
        <Content Include=".git\objects\c7\be03b6d43aaf39903a5e72b3d1df5d65d5e4b9" />
        <Content Include=".git\objects\c9\01868708e9714ad88a7cc2201651dd4a24f4af" />
        <Content Include=".git\objects\ca\47b48b722ebf3b87730ef7fc21b2be3cf4bdd6" />
        <Content Include=".git\objects\ce\079f4b378fab468559ec7580910f38367bac26" />
        <Content Include=".git\objects\d3\dafb473faedad2a8f4d889195579b11e9f10d9" />
        <Content Include=".git\objects\d6\9f6161a3b3a7058842a1d27218beaf6c9dc91b" />
        <Content Include=".git\objects\d7\607ae7af55578915ec58c7d361f56e86bfecff" />
        <Content Include=".git\objects\d7\d2ee6b052a88fccc4bc255f716344c0e21e31c" />
        <Content Include=".git\objects\d7\f1053952786ad8bf5aa157111cebcb17f33aa8" />
        <Content Include=".git\objects\d8\19ff060a9d2139e500ecd32bbdb7e0c932de7e" />
        <Content Include=".git\objects\d8\3498e18b16f444e2ab3aa13c13ca108115daa7" />
        <Content Include=".git\objects\d8\4c57e71a67f03f42558fb8597168720ac6bcaa" />
        <Content Include=".git\objects\db\7541149d4b061ebdef6f7e3b54973f5fc4ebeb" />
        <Content Include=".git\objects\e0\adf0c558b0cbe59629eadb0f4ebe41b9fe8efc" />
        <Content Include=".git\objects\e2\48693fd9c10624b83208144dba1615cdd71f1e" />
        <Content Include=".git\objects\e3\ce65c8fd82b77e859c172280534bf76e2bc6df" />
        <Content Include=".git\objects\e5\40514e22d3511f1ec84fde1acfe673efef8227" />
        <Content Include=".git\objects\e5\a710234d23655d7d0a9b4b729eda9e96f1f188" />
        <Content Include=".git\objects\e7\71a3a3dcdd64806ebb7b2260cf809dfec9231c" />
        <Content Include=".git\objects\e9\7ed929af9af1f1b36746108fb3dcc31f63f774" />
        <Content Include=".git\objects\ec\d03ba697493e0a3b6232659ff9843e78d1ed7f" />
        <Content Include=".git\objects\ee\65ba7c6b593be58cdf2e0029e7dab135f19d7f" />
        <Content Include=".git\objects\f0\19851db8794d391b8c05118b070234de0fb6ad" />
        <Content Include=".git\objects\f0\94ca9f1b1ff7d7dadb9b98242d4f8b96f2ea84" />
        <Content Include=".git\objects\f2\2bbde4e5980c70ca86b90cd58b6f6eb2dcf893" />
        <Content Include=".git\objects\f2\8ef706a9d8b897f8387440baff0aee8bed1535" />
        <Content Include=".git\objects\f3\0020d014147ced88ae3d45dc2a65fcd6cb5369" />
        <Content Include=".git\objects\f3\0c1b77663f2b9c5d2ac0829bc2c4a04429b609" />
        <Content Include=".git\objects\f3\1928898e42f48cd5c22d25185c86dadd47d065" />
        <Content Include=".git\objects\f4\3c3134b21df156428262feda4fa8353de9fc96" />
        <Content Include=".git\objects\f5\2c6f564817a2edc2d467dcbb0dd23606da7efc" />
        <Content Include=".git\objects\f5\aaf3660cab8a8bc36d2bbf36c2386af27f69d7" />
        <Content Include=".git\objects\f7\24d93604ba19262e524e572515edcddd2c6662" />
        <Content Include=".git\objects\f9\eba37f2ae90c8c94ed333cf668cb34e30a5a96" />
        <Content Include=".git\objects\fa\07b5cb1334306c0eadb4b71c63d9b468ee9a32" />
        <Content Include=".git\objects\fb\22a7fb03776ba2a896849d67ab71426dc95142" />
        <Content Include=".git\objects\fd\ac4113cac83bf91bb9ac3e404e4998cd910525" />
        <Content Include=".git\objects\fe\b87c76157dbc1dba274d3ab2d001ce1d47c1d5" />
        <Content Include=".git\objects\fe\fb160674dfa0a854d44dca299653d1d7bd2c8a" />
        <Content Include=".git\objects\ff\2ca06c7b9a3b988927fe88c34aa437a7027a9f" />
        <Content Include=".git\refs\heads\master" />
        <Content Include=".git\refs\remotes\origin\master" />
        <Content Include=".git\refs\tags\release-1.0.0" />
        <Content Include=".git\refs\tags\release-1.0.1" />
        <Content Include="bundles\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <Folder Include=".git\objects\info\" />
      <Folder Include=".git\objects\pack\" />
    </ItemGroup>
</Project>