<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>0.0.1</Version>
        <!-- The two lines below will set the output path for the binaries -->
        <OutputPath>M:\Work\MyRawMod\Builds\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <!-- Disable PDB file generation -->
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <!-- Disable generation of deps.json file -->
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
        <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
        <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include=".git\objects\info\" />
      <Folder Include=".git\objects\pack\" />
    </ItemGroup>
    <Target Name="CopyDLL" AfterTargets="Build">
        <Copy SourceFiles="$(OutDir)$(ProjectName).dll"
              DestinationFolder="M:\Work\MyRawMod\ManneuqinMods\MoreMannequinPoses\SPT_Runtime\user\mods\CustomMannequinPoseServer\"
              SkipUnchangedFiles="true" />
    </Target>
    <Target Name="CopyJson" AfterTargets="Build">
        <Copy SourceFiles="$(OutDir)\CustomMannequinPoseServer\PoseList.json"
              DestinationFolder="M:\Work\MyRawMod\ManneuqinMods\MoreMannequinPoses\SPT_Runtime\user\mods\CustomMannequinPoseServer\"
              SkipUnchangedFiles="true" />
    </Target>
</Project>